# Generated by Django 4.0.2 on 2022-02-09 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SaleReportApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SaleData',
            new_name='SaleData1',
        ),
    ]
