# Generated by Django 4.0.2 on 2022-02-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaleReportApp', '0002_rename_saledata_saledata1'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleData2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Region', models.CharField(max_length=255)),
                ('Country', models.CharField(max_length=255)),
                ('Item_Type', models.CharField(max_length=150)),
                ('Sales_Channel', models.CharField(max_length=150)),
                ('Order_Priority', models.CharField(max_length=10)),
                ('Order_Date', models.DateField()),
                ('Order_ID', models.IntegerField(default=0)),
                ('Ship_Date', models.DateField()),
                ('Units_Sold', models.IntegerField()),
                ('Unit_Price', models.FloatField()),
                ('Unit_Cost', models.FloatField()),
                ('Total_Revenue', models.FloatField()),
                ('Total_Cost', models.FloatField()),
                ('Total_Profit', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='SaleData1',
        ),
    ]
