# Generated by Django 4.0.2 on 2022-02-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaleReportApp', '0003_saledata2_delete_saledata1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saledata',
            name='Sales_Channel',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=150),
        ),
    ]
