# Generated by Django 4.0.2 on 2022-02-17 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SaleReportApp', '0004_alter_saledata_sales_channel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saledata',
            old_name='Country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='saledata',
            old_name='Item_Type',
            new_name='item_type',
        ),
        migrations.RenameField(
            model_name='saledata',
            old_name='Order_Date',
            new_name='order_date',
        ),
        migrations.RenameField(
            model_name='saledata',
            old_name='Order_ID',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='saledata',
            old_name='Order_Priority',
            new_name='order_priority',
        ),
        migrations.RenameField(
            model_name='saledata',
            old_name='Region',
            new_name='region',
        ),
        migrations.RenameField(
            model_name='saledata',
            old_name='Sales_Channel',
            new_name='sales_channel',
        ),
        migrations.RenameField(
            model_name='saledata',
            old_name='Ship_Date',
            new_name='ship_date',
        ),
        migrations.RenameField(
            model_name='saledata',
            old_name='Total_Cost',
            new_name='total_cost',
        ),
        migrations.RenameField(
            model_name='saledata',
            old_name='Total_Profit',
            new_name='total_profit',
        ),
        migrations.RenameField(
            model_name='saledata',
            old_name='Total_Revenue',
            new_name='total_revenue',
        ),
        migrations.RenameField(
            model_name='saledata',
            old_name='Unit_Cost',
            new_name='unit_cost',
        ),
        migrations.RenameField(
            model_name='saledata',
            old_name='Unit_Price',
            new_name='unit_price',
        ),
        migrations.RenameField(
            model_name='saledata',
            old_name='Units_Sold',
            new_name='units_sold',
        ),
    ]
